 // 1. Print a matrix in a spiral order.
 // 2. Matrix Search.(use the sorting order for the efficient algorithm)
//  3. Given an array arr[] of size N. The task is to find the first smallest (element) repeating element in the array of integres. i.e an
//     element that occurs more than once and whose index is smallest.
        // e.g : [1,3,4,2,5,7,4,3,2,9,0,6,3]         
        //Repeating elements : 2 -------3 times
        //                     3 ------- 2 times
        //Smallest element : 2 