 // 1. Print a matrix in a spiral order.
 // 2. Assign Roll number to Students according to Alphabetically order.
 // 3. Given an array A[] consisting of only 0s, 1s, and 2s. 
 //        The task is to write a function that sorts the given array. 
 //        The functions should put all 0s first, then all 1s and all 2s in last.
 // 5. Count pairs with the given sum.
 // 6. Move all the -ve elements on the left side of the array.
 // 7. CREATE A STACK OPERATION OF ARRAY IN C++.